# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permission_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grade1',
            },
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=6, unique=True)),
                ('stu_sex', models.BooleanField(default=0)),
                ('stu_birth', models.DateField(default=0)),
                ('stu_delete', models.BooleanField(default=0)),
                ('stu_create_time', models.DateField(auto_now_add=True)),
                ('stu_operate_time', models.DateField(auto_now_add=True)),
                ('stu_tel', models.CharField(max_length=11)),
                ('stu_yuwen', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('stu_shuxue', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Grade1')),
            ],
            options={
                'db_table': 'stu1',
            },
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_addr', models.CharField(max_length=30)),
                ('stu_age', models.IntegerField()),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Student1')),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
    ]
