# Generated by Django 2.0.6 on 2018-07-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_teacher_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-no',)},
        ),
    ]
