# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180530_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='delete',
            field=models.BooleanField(default=True),
        ),
    ]
